@Library('infra-jenkins-shared-library@feat/sonarqube') _
pipeline {


    agent {
        kubernetes {
            defaultContainer 'sonar'
            idleMinutes 1
            yaml agentLauncher(name: "sonarScannerPodTemplate")
        }
    }
    options {
        ansiColor('xterm')
        disableConcurrentBuilds(abortPrevious: true)
        //only keep last 5 builds and artifacts
        buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
    }

    environment {
        SONAR_TOKEN = credentials('sonarqube-credentials-token')
    }

    stages {
        stage('Sonarqube Scan') {
            steps {
                script {
                    sonarScanner(project: "test", sourcePath: ".")
                }
            }
        }
    }
}
